---
- name: Perform initial setup
  import_playbook: initial-setup.yaml

- hosts: all
  environment:
    OS_CLOUD: devstack-admin

  tasks:
    - include_tasks: ssh-key.yaml

    - include_tasks: centos8-image.yaml
      when:
        - metalsmith_whole_disk_image is defined
        - metalsmith_partition_image is defined

    - include_tasks: cirros-image.yaml
      when:
        - metalsmith_whole_disk_image is undefined
        - metalsmith_partition_image is undefined

    - name: Test a whole-disk image
      include_tasks: exercise.yaml
      vars:
        metalsmith_image: "{{ metalsmith_whole_disk_image }}"
        metalsmith_image_checksum: "{{ metalsmith_whole_disk_checksum | default('') }}"
        metalsmith_root_size:
        # NOTE(dtantsur): cannot specify swap with whole disk images
        metalsmith_swap_size:

    - name: Test a partition image
      include_tasks: exercise.yaml
      vars:
        metalsmith_image: "{{ metalsmith_partition_image }}"
        metalsmith_image_checksum: "{{ metalsmith_partition_checksum | default('') }}"
        metalsmith_image_kernel: "{{ metalsmith_partition_kernel_image | default('') }}"
        metalsmith_image_ramdisk: "{{ metalsmith_partition_ramdisk_image | default('') }}"
