# Optional parameters
metalsmith_capabilities: {}
metalsmith_extra_args:
metalsmith_netboot: false
metalsmith_nics: []
metalsmith_root_size:
metalsmith_ssh_public_keys: []
metalsmith_user_name: metalsmith

# Wait parameters
metalsmith_provisioning_timeout:
